import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body className="{inter.className}">
                <header>
                    <h1 className="bg-orange-500">Some About Me header</h1>
                </header>
                {children}
                <footer>
                    <p>Some About Me footer</p>
                </footer>
            </body>
        </html>
    );
}
